{"name": "Test: Homepage Load After Login with locked_out_user", "status": "passed", "attachments": [{"name": "Login Error Message", "source": "05729f42-1e74-4edc-b183-4ee951d5d8c3-attachment.txt", "type": "text/plain"}, {"name": "Login Failure Screenshot", "source": "87ce68a2-a1af-41da-b1d9-5a70ac858939-attachment.png", "type": "image/png"}], "parameters": [{"name": "username", "value": "'locked_out_user'"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1744806192061, "stop": 1744806192679, "uuid": "24c23760-46b7-4960-9e03-da3c78fdaefc", "historyId": "77de83f228ca69fccea7f647998cb84e", "testCaseId": "8692e52510eaea2147cae97be19aae5c", "fullName": "tests.test_login_valid_credentials#test_homepage_load_after_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_valid_credentials"}, {"name": "host", "value": "Kaustubh-Nitro5"}, {"name": "thread", "value": "16980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_valid_credentials"}]}